/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/cli_logger.py:57: FutureWarning: Not all Ray CLI dependencies were found. In Ray 1.4+, the Ray CLI, autoscaler, and dashboard will only be usable via `pip install 'ray[default]'`. Please update your install command.
  warnings.warn(
Traceback (most recent call last):
  File "test_enigmx.py", line 7, in <module>
    ray.init(include_dashboard=(False),ignore_reinit_error=(True))
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ray/worker.py", line 802, in init
    _global_node = ray.node.Node(
  File "/usr/local/lib/python3.8/dist-packages/ray/node.py", line 242, in __init__
    self.start_ray_processes()
  File "/usr/local/lib/python3.8/dist-packages/ray/node.py", line 885, in start_ray_processes
    ray._private.services.determine_plasma_store_config(
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/services.py", line 1720, in determine_plasma_store_config
    raise ValueError(
ValueError: The configured object store size (12.090916864 GB) exceeds /dev/shm size (12.090916864 GB). This will harm performance. Consider deleting files in /dev/shm or increasing its size with --shm-size in Docker. To ignore this warning, set RAY_OBJECT_STORE_ALLOW_SLOW_STORAGE=1.
/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/cli_logger.py:57: FutureWarning: Not all Ray CLI dependencies were found. In Ray 1.4+, the Ray CLI, autoscaler, and dashboard will only be usable via `pip install 'ray[default]'`. Please update your install command.
  warnings.warn(
Traceback (most recent call last):
  File "test_enigmx.py", line 7, in <module>
    ray.init(include_dashboard=(False),ignore_reinit_error=(True))
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ray/worker.py", line 802, in init
    _global_node = ray.node.Node(
  File "/usr/local/lib/python3.8/dist-packages/ray/node.py", line 242, in __init__
    self.start_ray_processes()
  File "/usr/local/lib/python3.8/dist-packages/ray/node.py", line 885, in start_ray_processes
    ray._private.services.determine_plasma_store_config(
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/services.py", line 1720, in determine_plasma_store_config
    raise ValueError(
ValueError: The configured object store size (12.090916864 GB) exceeds /dev/shm size (12.090916864 GB). This will harm performance. Consider deleting files in /dev/shm or increasing its size with --shm-size in Docker. To ignore this warning, set RAY_OBJECT_STORE_ALLOW_SLOW_STORAGE=1.
